# https://github.com/sshd911/visual-lineage-pacman
push:
	git add .
	git commit -m 'fix'
	git push origin HEAD

# dev commands
run:
	sudo python app.py
format: 
	black . --line-length=1000
env:
	pipreqs --force 

# installation
install:
	pip install -r requirements.txt
